name: "build"

on:
  push:
    tags:
      - 2.*

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          DRONE_VERSION: ${{ github.ref_name }}
        with:
          push: true
          tags: |
            suyar/drone-server:${{ github.ref_name }}
            suyar/drone-server:2